ogcio/logto

- .github/pull_request_template.md
- Dockerfile
- docker-compose.yml
**New PR based on dev instead of master**
- [14976](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/14976)
Expose `330x` ports to avoid colliding with `life-events` services locally
> Chore: update dockerfile to expose 330x ports

- packages/cli/src/commands/database/ogcio/organizations-rbac.ts
- packages/cli/src/commands/database/ogcio/resources-rbac.ts
The seeder was wrongly assigning permissions to the admin role
- [] **New feature**
> Fix: permissions assignment

- packages/cli/src/commands/database/ogcio/organizations.ts
- packages/cli/src/commands/database/ogcio/queries.ts
We have to update a configuration on db when creating an organization for the first time
> fix(cli): set organization as created for default tenant

- docker-compose-local.yml
- packages/cli/src/commands/database/ogcio/applications.ts
- packages/cli/src/commands/database/ogcio/common-rbac.ts
- packages/cli/src/commands/database/ogcio/index.ts
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/ogcio.ts
- packages/cli/src/commands/database/ogcio/organizations-rbac.ts
- packages/cli/src/commands/database/ogcio/organizations.ts
- packages/cli/src/commands/database/ogcio/queries.ts
- packages/cli/src/commands/database/ogcio/resources-rbac.ts
- packages/cli/src/commands/database/ogcio/resources.ts
Seed entities based on a JSON file
> Feature: seeder by json

- docker-compose-local.yml
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
When running locally, now it runs db migrations, if any
> fix(cli): deploy db alteration on run

- Dockerfile
- package.json
Manage the possibility to set single variables when invoking a new `ogcio:start` command
> Chore: env for pipeline

- docker-compose-local.yml
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
Fixed seeder adding trailing slash
> Fix: fixed seeder using trailing slash

- docker-compose-local.yml
- packages/cli/src/commands/database/ogcio/applications.ts
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/queries.ts
Seed fixed applications ids and secrets to be able to reuse them when cleaning db locally
> Chore: seed fixed ids

- docker-compose-local.yml
- packages/cli/src/commands/database/ogcio/applications.ts
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/queries.ts
This change adds db volume to docker-compose file to persist data across restarts
> chore(db persist) Added volume config to persist db data to volume

- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/ogcio.ts
- packages/cli/src/commands/database/ogcio/sign-in-experiences.ts
- [17549](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?workitem=17549)
Seeding custom sign in experience config.
N/A
> feat(cli): seeding custom sign in experience config

- README.OGCIO.md
Updated the README file with some steps to follow to sync with new main repository releases
> Chore: write guide to sync with main repo

- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/ogcio.ts
- packages/cli/src/commands/database/ogcio/webhooks.ts
- [17770](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/17770)
Seed webhooks config
N/A
> feat(cli): seed webhooks config

- packages/cli/src/commands/database/ogcio/ogcio-seeder-deployment.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- [17695](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?workitem=17695)
Seed mygovid connector
N/A
> feat(cli): seed mygovid connector

- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/core/src/libraries/ogcio-user.ts
- packages/core/src/routes/interaction/actions/submit-interaction.ts
- [17584](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?System.Tags=payments&workitem=17584)
Resolve custom user role based on the user's email's domain..
N/A
> feat(core): resolve custom user role based on user emails domain

- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/core/src/libraries/ogcio-user.ts
- [17893](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?System.Tags=payments&workitem=17893)
Update seeder.
N/A
> feat(cli): update seeder

- README.OGCIO.md
- docker-compose-db.yml
- docker-compose-local.yml
- [17551](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?System.Tags=payments&workitem=17551)
Documentation to describe the installation and configuration process of Logto in order to run it natively, also describes the custom seeder.
N/A
> chore: documentation

- docker-compose-local.yml
- packages/cli/src/commands/database/ogcio/common-rbac.ts
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/organizations.ts
- [17893](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?System.Tags=payments&workitem=17893)
Update seeder data.
N/A
> feat(cli): update seeder data

- packages/core/src/libraries/ogcio-user.ts
- [17584](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_boards/board/t/Life%20Events/Stories?System.Tags=payments&workitem=17584)
fix: user role assign
N/A
> fix: user role assign

- azure_pipelines.yml
> fix(cli): fix logto pipeline

- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
- packages/cli/src/commands/database/ogcio/ogcio.ts
- packages/cli/src/commands/database/ogcio/organizations-rbac.ts
- packages/cli/src/commands/database/ogcio/resources-rbac.ts
fix(cli): fix seeder to handle empty data
> fix(cli): fix seeder to handle empty data

- pipeline-variables/uat.yml
> feat: logto uat changes

- Dockerfile
remove seed commands from dockerfile
N/A
> Test migration command in Terraform

- Dockerfile
- packages/cli/src/commands/database/ogcio/organizations-rbac.ts
- [18810](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/18810)
Deploy to UAT changes to Dockerfile entrypoint
N/A
> [18810] Deploy to UAT

- packages/cli/src/commands/database/ogcio/applications.ts
- packages/cli/src/commands/database/ogcio/ogcio-seeder.ts
Seed multiple redurect URIs for applications.
> feat(cli): seed multiple redurect uris

- README.OGCIO.md
- [XXX](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/XXX)
Please include a summary of the changes and the related issue.
Update docs on Docker remote images
N/A
> docs: update docker remote images instructions

- packages/connectors/connector-mygovid/src/index.ts
- packages/connectors/connector-mygovid/src/types.ts
Fixed MyGovId connector mapping for names
> Fix(mygovid): connector fix parsing

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
Added permissions for the `scheduler-api` resource
N/A
> Feat(ogcio): scheduler permissions

- README.OGCIO.md
- [18097](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/18097)
Extended documentation to add git rerere instructions and explanation for easier conflict resolution
N/A
> [18097]: Extend docs on conflict resolution

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- [16988](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/16988)
Seed HOME building blocks application
N/A
> [16988] Home bb application

- packages/connectors/connector-ogcio-entraid/CHANGELOG.md
- packages/connectors/connector-ogcio-entraid/README.md
- packages/connectors/connector-ogcio-entraid/logo.svg
- packages/connectors/connector-ogcio-entraid/package.json
- packages/connectors/connector-ogcio-entraid/src/constant.ts
- packages/connectors/connector-ogcio-entraid/src/index.test.ts
- packages/connectors/connector-ogcio-entraid/src/index.ts
- packages/connectors/connector-ogcio-entraid/src/types.ts
- pnpm-lock.yaml
- [19986](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/19986)
As the Microsoft Azure AD LogTo connector has limitations around retrieving the connected user e-mail via userinfo, we fork the connector to create a new one that would coalesce between the email and the upn fields.
N/A
> feat(ogcio): entraid connector

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
Adds seeder for upload app
N/A
> chore: seed upload app

- azure_pipelines.yml
- pipeline-templates/push_image.yml
- [XXX](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/XXX)
Please include a summary of the changes and the related issue.
N/A
> chore: fix pipelines

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- [19987](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/19987)
Seed data for OGCIO EntraID connector.
N/A
> feat: seed entraid connector

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- changed upoload api port from 8007 to 8008
Please include a summary of the changes and the related issue.
> fix: upload-api app port

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- [19876](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/19876)
MyGovId connector sync set to true to always have user data updated
- [] **New feature**
> Fix(OGCIO): 19876 always sync user profile

- packages/cli/src/commands/database/ogcio/applications.ts
- [19875](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/19875)
Shorter refresh token, set to 1 day, so the users will be logged out in 1 day after the last time they requested a token
> Chore(OGCIO): shorter refresh token

- packages/cli/src/commands/database/ogcio/ogcio-seeder-local.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder-testing.json
- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- Addes permission to upload-api
N/A
> feat(cli): new permissions

- mygovid-mock-service/src/routes/static/mock-login.html
> chore: add new mock user

- packages/cli/src/commands/database/ogcio/ogcio-seeder.json
- [20280](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/20280)
We want to seed the analytics related data on remote environments (dev, sta, uat, prd).
N/A
> feat(cli): add analytics seeding
